name: Run Cypress Tests

description: Run Cypress tests

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Build the app
      run: make build up
      shell: bash

    - name: Run Cypress tests
      shell: bash
      run: cd frontend && npm run cypress:run
